config/routes.rb
Rails.application.routes.draw do
  get 'sign_up',  to:  'users#new'
  get 'login',  to:  'sessions#new'
  post 'login' ,  to: 'sessions#create'
  get 'logout',  to: 'sessions#destroy'
  resources :users, only: [:new, :create, :show]
  resources :invitations, only: [:index,  :new, :create]
  resources :events
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations

  validates :title, :description, :date, presence: true, length: { maximum: 50 }

  scope :comming_events, -> { where('date > ?', DateTime.now) }
  scope :past_events, -> { where('date < ?', DateTime.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: 'attendee_id'
  belongs_to :attended_event, class_name: 'Event', foreign_key: 'attended_event_id'

  validates :attendee_id, uniqueness: { scope: :attended_event_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations
  has_many :events, foreign_key: :creator_id
  validates :name, :email, presence: { message: '- The field can not be empty' }
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP,
                                                message: '- Please type an email' }

  def user_comming_events
    attended_events.comming_events
  end

  def user_past_events
    attended_events.past_events
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_validation
  helper_method :user_signed_in?
  helper_method :show_user_name

  def current_user
    User.find_by(id: session[:creator_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def user_validation
    return 'Log out' if user_signed_in?

    'signed_in'
  end

  def show_user_name
    return current_user.name if current_user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @upcomming_events = Event.comming_events
    @past_events = Event.past_events
  end

  def show
    @event = Event.find(params[:id])
    @creator = User.find(@event.creator_id).name
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = 'Event successfully created'
      redirect_to @event
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @invitation = Invitation.new
    @users_list = User.all
  end

  def create
    @invitation = Invitation.new(atendee_params)
    @users_list = User.all
    if @invitation.save
      flash[:success] = 'Invitantion successfully created'
      redirect_to new_invitation_path
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  private

  def atendee_params
    params.require(:invitation).permit(:attended_event_id, :attendee_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user
      session[:creator_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully!'
    else
      flash.now[:alert] = 'Email incorrect'
      render :new
    end
  end

  def destroy
    session[:creator_id] = nil
    redirect_to login_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(params[:id])
    @created_past_events = current_user.events.past_events
    @created_upcomming_events = current_user.events.comming_events
    @upcomming_events = current_user.user_comming_events
    @past_events = current_user.user_past_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def error_validator(user)
    return unless user.errors.any?

    list = "<ul class='has-text-danger'>"
    user.errors.full_messages.each do |message|
      list += "<li class='has-text-danger'>#{message}</li>"
    end
    list += '</ul>'
    list.html_safe
  end
end

app/views/events/_event_card.html.erb
<div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
          <p class="title is-4"><%= ce.title%></p>
          <p class="subtitle is-6"><%= ce.creator.name%></p>
        </div>
      </div>
        <div class="content">
          <%= ce.description%>
          <div><%= ce.date%> </div>
          <%= link_to 'Show', event_path(ce), class: 'button'%>
        </div>
        
      </div>
    </div>

app/views/events/index.html.erb
<h1 class="title mt-5">Comming Events</h1>
  <div class="columns">
  <% @upcomming_events.each do |ce| %>
    <%= render partial: 'events/event_card', :locals => {:ce => ce} %> 
  <% end %>
</div>
<h1 class="title"> Past Events</h1>
<div class="columns">
  <% @past_events.each do |ce|%>
  <%= render partial: 'events/event_card', :locals => {:ce => ce} %> 
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= form_with(model: @event, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4"><%= @event.title %></p>
      </div>
    </div>

    <div class="content">
      <p><strong>Description: </strong><%= @event.description %></p>
      <p ><strong>Date: </strong>  <%= @event.date %></p>
      <p >By <%= @creator %></p>
    </div>
  </div>
</div>



<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4">Attendees</p>
      </div>
    </div>

    <div class="content">
      <% @event.invitations.each do |att| %>
        <%= User.find(att.attendee_id).name %><br>
      <% end %>
    </div>
  </div>
</div>

app/views/invitations/new.html.erb
<% @users_list.each do |user| %>
  <div class="card mt-3">
    <header class="card-header">
      <p class="card-header-title">
        <%=user.name%>
      </p>
      <a href="#" class="card-header-icon" aria-label="more options">
        <span class="icon">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </a>
    </header>
    <footer class="card-footer is-flex is-align-items-center">
      <%= form_with(model: @invitation, local: true) do |form| %>
        <div>
          <%= form.hidden_field :attendee_id, value: user.id %>
        </div>
        <div class="container p-3 is-flex is-align-items-center">
          <%= form.label "select an event" , class: "mr-3"%>
          <%= form.collection_select(:attended_event_id, Event.all, :id, :title,
                  { multiple: true, size: 3 }, class: "select mr-3" )%>
          <%= form.submit "Invite" ,class: "button"%>
        </div>
      <% end %> 
    </footer>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar has-background-primary" role="navigation" aria-label="main navigation">

  <div id="navbarBasicExample" class="navbar-menu pl-2">
    <div class="navbar-start">
      <%= link_to 'Events', root_url, class: 'navbar-item is-size-3'%>
      <% if user_signed_in?%>
        <%= link_to 'Invite', new_invitation_path, class: 'navbar-item'%>
        <%= link_to 'My events', user_path(current_user.id), class: 'navbar-item' %>
      <% end %>
    </div>

    <div class="navbar-end">
      <% if user_signed_in? %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= current_user.name %>
        </a>

        <div class="navbar-dropdown">
          <%= link_to 'New Event', new_event_path, class: 'navbar-item' %>
          <hr class="navbar-divider">
          <%= link_to 'Log out', logout_path, class: 'navbar-item'%>
        </div>
      </div>
      <% else %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to 'Sign up', sign_up_path, class: 'button is-primary'%>
            <%= link_to 'Log in', login_path, class: 'button is-light'%>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>

    <%= render 'layouts/navbar'%>
    <% flash.each do |key, value|%>
      <p class="has-background-info has-text-white-bis p-3"><%=value%></p> 
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>
<%= error_validator(@user)%>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to user_validation ,  logout_path %>

app/views/users/show.html.erb
<div class="card mt-6">
  <header class="card-header has-background-success ">
    <p class="card-header-title is-size-3 has-text-primary-light">
      User details
    </p>
    <a href="#" class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </a>
  </header>
  <div class="card-content">
    <div class="content">
    <p><strong>Name :</strong> <%= current_user.name %><br /></p>
    <p><strong>Email :</strong> <%= current_user.email %><br /></p>
    </div>
  </div>
</div>
<div class="card mt-5 ">
  <header class="card-header">
    <p class="card-header-title is-size-5 has-background-light">
      My events
    </p>
  </header>
  <div class="card-content">
    <div class="card">
    <header class="card-header">
      <p class="card-header-title is-size-5 has-background-light">
        My past event
      </p>
    </header>
    <div class="content">
      <% @created_past_events.each do |e|%>
          <p><strong>Event name</strong> <br><%= e.title %></p>
          <p><strong>Event description</strong> <br><%= e.description %></p>
          <p><strong>Event date</strong> <br><%= e.date %></p>
          <hr>
      <% end %>
    </div>
    </div>
    <div class="card mt-3">
      <header class="card-header">
        <p class="card-header-title is-size-5 has-background-light">
          My upcoming events
        </p>
      </header >
      
      <div class="content p-2">
        <% @created_upcomming_events.each do |e|%>
            <p><strong>Event name</strong> <br><%= e.title %></p>
            <p><strong>Event description</strong> <br><%= e.description %></p>
            <p><strong>Event date</strong> <br><%= e.date %></p>
            <hr>
        <% end %>
      </div>    
    </div>
    
  </div>
</div>

<div class="card mt-5 ">
  <header class="card-header">
    <p class="card-header-title is-size-5 has-background-light">
      Invited upcoming events
    </p>
  </header>
  <div class="card-content">
    <div class="content">
      <% @upcomming_events.each do |pe|%>
        <p><strong>Event name</strong> <br><%= pe.title %></p>
        <p><strong>Event description</strong> <br><%= pe.description %></p>
        <p><strong>Event date</strong> <br><%= pe.date %></p>
        <hr>
      <% end %>
    </div>
  </div>
</div>

<div class="card mt-5 ">
  <header class="card-header">
    <p class="card-header-title is-size-5 has-background-light">
      Invited Past events
    </p>
  </header>
  <div class="card-content">
    <div class="content">
      <% @past_events.each do |pe|%>
        <p><strong>Event name</strong> <br><%= pe.title %></p>
        <p><strong>Event description</strong> <br><%= pe.description %></p>
        <p><strong>Event date</strong> <br><%= pe.date %></p>
        <hr>
      <% end %>
    </div>
  </div>
</div>